import type { AppState } from "./types";

export const INDIAN_CITIES = [
  "Delhi",
  "Mumbai",
  "Pune",
  "Bangalore",
  "Chennai",
  "Kolkata",
  "Hyderabad",
  "Ahmedabad",
  "Jaipur",
  "Lucknow",
  "Surat",
  "Nagpur",
  "Indore",
  "Chandigarh",
  "Kochi",
];

export const TRUCK_TYPES = [
  "Tata ACE (1T)",
  "Pickup (2T)",
  "LCV (5T)",
  "Container 14ft (7.5T)",
  "Container 20ft (12T)",
  "Container 32ft (16T)",
  "Mazda (3.5T)",
  "Eicher 19ft (9T)",
  "Taurus (16T)",
  "32 Ton Trailer",
];

export const CARGO_TYPES = [
  "General Goods",
  "FMCG",
  "Textiles",
  "Chemicals",
  "Electronics",
  "Automotive Parts",
  "Construction Material",
  "Food & Beverages",
  "Pharmaceuticals",
  "Furniture",
];

const now = Date.now();
const iso = (daysAgo: number, hoursAgo = 0) =>
  new Date(now - daysAgo * 86400000 - hoursAgo * 3600000).toISOString();

export function createSeedState(): AppState {
  return {
    sessionUserId: null,
    users: [
      {
        id: "u-shipper-1",
        name: "Ananya Sharma",
        email: "shipper@cargolink.demo",
        phone: "+91 98100 12345",
        password: "demo1234",
        role: "SHIPPER",
        company: "Sharma Textiles Pvt Ltd",
        city: "Delhi",
        status: "active",
        createdAt: iso(120),
      },
      {
        id: "u-driver-1",
        name: "Rahul Verma",
        email: "driver@cargolink.demo",
        phone: "+91 98100 54321",
        password: "demo1234",
        role: "DRIVER",
        city: "Mumbai",
        status: "active",
        createdAt: iso(90),
        vehicleId: "v-1",
      },
      {
        id: "u-fleet-1",
        name: "Kiran Transports",
        email: "fleet@cargolink.demo",
        phone: "+91 98200 11111",
        password: "demo1234",
        role: "FLEET_OPERATOR",
        company: "Kiran Transports",
        city: "Delhi",
        status: "active",
        createdAt: iso(80),
      },
      {
        id: "u-admin-1",
        name: "CARGOLINK Admin",
        email: "admin@cargolink.demo",
        password: "admin1234",
        role: "ADMIN",
        status: "active",
        createdAt: iso(200),
      },
    ],
    vehicles: [
      {
        id: "v-1",
        ownerId: "u-driver-1",
        number: "MH-12-AB-3456",
        truckType: "32 Ton Trailer",
        capacity: 32,
        bodyType: "Open Trailer",
        currentLocation: "Mumbai",
        driverName: "Rahul Verma",
        driverPhone: "+91 98100 54321",
        availability: "available",
        status: "active",
        createdAt: iso(80),
      },
      {
        id: "v-2",
        ownerId: "u-fleet-1",
        number: "DL-01-CD-7890",
        truckType: "Container 20ft (12T)",
        capacity: 12,
        bodyType: "Container",
        currentLocation: "Delhi",
        driverName: "Suresh Kumar",
        driverPhone: "+91 98200 22222",
        availability: "available",
        status: "active",
        createdAt: iso(70),
      },
      {
        id: "v-3",
        ownerId: "u-fleet-1",
        number: "DL-01-EF-1122",
        truckType: "Taurus (16T)",
        capacity: 16,
        bodyType: "Open Body",
        currentLocation: "Jaipur",
        driverName: "Vikram Singh",
        driverPhone: "+91 98200 33333",
        availability: "on-trip",
        status: "active",
        createdAt: iso(60),
      },
      {
        id: "v-4",
        ownerId: "u-fleet-1",
        number: "HR-55-GH-4455",
        truckType: "Container 32ft (16T)",
        capacity: 16,
        bodyType: "Container",
        currentLocation: "Delhi",
        driverName: "Amit Yadav",
        driverPhone: "+91 98200 44444",
        availability: "maintenance",
        status: "active",
        createdAt: iso(50),
      },
    ],
    shipments: [
      {
        id: "s-1",
        ref: "CL-28491",
        shipperId: "u-shipper-1",
        pickup: "Delhi",
        drop: "Mumbai",
        cargoType: "FMCG",
        weight: 12,
        truckType: "32 Ton Trailer",
        pickupDate: new Date(now - 86400000).toISOString().slice(0, 10),
        pickupTime: "09:00",
        budget: 82000,
        instructions: "Handle with care. Palletized loading.",
        status: "COMPLETED",
        createdAt: iso(6),
      },
      {
        id: "s-2",
        ref: "CL-28512",
        shipperId: "u-shipper-1",
        pickup: "Delhi",
        drop: "Pune",
        cargoType: "Textiles",
        weight: 10,
        truckType: "Container 20ft (12T)",
        pickupDate: new Date(now + 86400000).toISOString().slice(0, 10),
        pickupTime: "10:30",
        budget: 88000,
        status: "SEARCHING_FOR_TRUCK",
        createdAt: iso(2),
      },
      {
        id: "s-3",
        ref: "CL-28533",
        shipperId: "u-shipper-1",
        pickup: "Delhi",
        drop: "Ahmedabad",
        cargoType: "General Goods",
        weight: 8,
        truckType: "Container 14ft (7.5T)",
        pickupDate: new Date(now - 86400000).toISOString().slice(0, 10),
        pickupTime: "08:00",
        budget: 56000,
        status: "IN_TRANSIT",
        createdAt: iso(4),
      },
    ],
    loads: [
      {
        id: "l-1",
        ref: "LD-10421",
        shipmentId: "s-2",
        pickup: "Delhi",
        drop: "Pune",
        distance: 1460,
        cargoType: "Textiles",
        weight: 10,
        truckType: "Container 20ft (12T)",
        price: 88000,
        pickupDate: new Date(now + 86400000).toISOString().slice(0, 10),
        pickupTime: "10:30",
        status: "open",
        createdAt: iso(2),
      },
      {
        id: "l-2",
        ref: "LD-10422",
        pickup: "Mumbai",
        drop: "Pune",
        distance: 148,
        cargoType: "FMCG",
        weight: 12,
        truckType: "32 Ton Trailer",
        price: 18500,
        pickupDate: new Date(now + 86400000).toISOString().slice(0, 10),
        pickupTime: "14:00",
        status: "open",
        createdAt: iso(1),
      },
      {
        id: "l-3",
        ref: "LD-10423",
        pickup: "Mumbai",
        drop: "Surat",
        distance: 262,
        cargoType: "Chemicals",
        weight: 14,
        truckType: "32 Ton Trailer",
        price: 19800,
        pickupDate: new Date(now + 2 * 86400000).toISOString().slice(0, 10),
        pickupTime: "09:00",
        status: "open",
        createdAt: iso(1),
      },
      {
        id: "l-4",
        ref: "LD-10424",
        pickup: "Mumbai",
        drop: "Ahmedabad",
        distance: 524,
        cargoType: "General Goods",
        weight: 11,
        truckType: "32 Ton Trailer",
        price: 38500,
        pickupDate: new Date(now + 3 * 86400000).toISOString().slice(0, 10),
        pickupTime: "08:30",
        status: "open",
        createdAt: iso(1),
      },
      {
        id: "l-5",
        ref: "LD-10425",
        pickup: "Jaipur",
        drop: "Delhi",
        distance: 280,
        cargoType: "Furniture",
        weight: 8,
        truckType: "Taurus (16T)",
        price: 22000,
        pickupDate: new Date(now + 86400000).toISOString().slice(0, 10),
        pickupTime: "11:00",
        status: "open",
        createdAt: iso(0, 6),
      },
    ],
    trips: [
      {
        id: "t-1",
        ref: "TRP-20841",
        shipmentId: "s-1",
        vehicleId: "v-1",
        driverId: "u-driver-1",
        shipperId: "u-shipper-1",
        pickup: "Delhi",
        drop: "Mumbai",
        status: "COMPLETED",
        currentLocation: "Mumbai",
        eta: "Delivered",
        progress: 100,
        startedAt: iso(5, 4),
        completedAt: iso(1),
        pickupCode: "4821",
        deliveryCode: "9302",
        earnings: 82000,
        createdAt: iso(5, 6),
      },
      {
        id: "t-2",
        ref: "TRP-20877",
        shipmentId: "s-3",
        vehicleId: "v-3",
        driverId: "u-fleet-1",
        shipperId: "u-shipper-1",
        pickup: "Delhi",
        drop: "Ahmedabad",
        status: "IN_TRANSIT",
        currentLocation: "Near Jaipur",
        eta: "Today, 21:40",
        progress: 62,
        startedAt: iso(3, 2),
        earnings: 56000,
        createdAt: iso(3, 4),
      },
    ],
    matches: [],
    notifications: [
      {
        id: "n-1",
        userId: "u-shipper-1",
        type: "delivery_completed",
        title: "Shipment delivered",
        message: "Shipment CL-28491 (Delhi → Mumbai) has been delivered.",
        read: true,
        createdAt: iso(1),
        href: "/dashboard/tracking?ref=CL-28491",
      },
      {
        id: "n-2",
        userId: "u-shipper-1",
        type: "new_shipment",
        title: "Shipment created",
        message: "Shipment CL-28512 is now searching for a truck.",
        read: false,
        createdAt: iso(2),
        href: "/dashboard/shipments",
      },
      {
        id: "n-3",
        userId: "u-driver-1",
        type: "return_match",
        title: "Return load opportunities",
        message: "3 return loads found near Mumbai for your truck.",
        read: false,
        createdAt: iso(0, 5),
        href: "/dashboard/matching",
      },
    ],
    transactions: [
      {
        id: "tx-1",
        userId: "u-driver-1",
        type: "earnings",
        amount: 82000,
        label: "Trip TRP-20841 · Delhi → Mumbai",
        status: "completed",
        createdAt: iso(1),
      },
      {
        id: "tx-2",
        userId: "u-shipper-1",
        type: "payment",
        amount: 82000,
        label: "Shipment CL-28491 · Delhi → Mumbai",
        status: "completed",
        createdAt: iso(1),
      },
      {
        id: "tx-3",
        userId: "u-fleet-1",
        type: "earnings",
        amount: 56000,
        label: "Trip TRP-20877 · Delhi → Ahmedabad",
        status: "pending",
        createdAt: iso(1, 6),
      },
    ],
  };
}
